### ISSUE TITLE
PING/PONG timeout problems

### ISSUE THREAD

**Issue by sixlettervariables** [nataly87s/SimpleNatsClient#8]
While working on a benchmark for the client I ran into what appears to be a problem with the PING timeout:

```
Publish Only (5s PING/PONG interval, 10s PING timeout)
Connected.
1000000 in 00:00:07.2025492 (138839.73/s)
Publish Only (5s PING/PONG interval, 5s PING timeout)
Connected.
Exception encountered on test 704499 of 1000000 (00:00:05.0159564)
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
   at SimpleNatsClient.Connection.TcpConnection.<Write>d__8.MoveNext() in .\SimpleNatsClient\SimpleNatsClient\Connection\TcpConnection.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimpleNatsClient.Connection.NatsConnection.<Write>d__27.MoveNext() in .\SimpleNatsClient\SimpleNatsClient\Connection\NatsConnection.cs:lne 186
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimpleNatsClient.NatsClient.<Publish>d__11.MoveNext() in .\SimpleNatsClient\SimpleNatsClient\NatsClient.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Tasktask)
   at BenchmarkTest.Benchmark.<BenchmarkPublishOnly>d__1.MoveNext() in .\SimpleNatsClient\benchmark\Benchmark.cs:line 41
```
Relevant benchmark source:
```csharp
    static async Task BenchmarkPublishOnly(NatsOptions options = null, int testCount = 10000, int payloadSize = 8)
    {
      int test = 0;
      byte[] payload = new byte[payloadSize];
      Stopwatch sw = null;
      try
      {
        using (var c = await NatsClient.Connect(options: options))
        {
          c.Connection.OnConnect.Subscribe(_ => Console.WriteLine("Connected."));
          sw = Stopwatch.StartNew();
          for (test = 0; test < testCount; ++test)
          {
            await c.Publish("test-subject", payload);
          }
          sw.Stop();
          Console.WriteLine($"{testCount} in {sw.Elapsed} ({testCount / sw.Elapsed.TotalSeconds:0.00}/s)");
        }
      }
      catch (Exception ex)
      {
        sw.Stop();
        Console.WriteLine($"Exception encountered on test {test} of {testCount} ({sw?.Elapsed})");
        Console.WriteLine(ex);
      }
    }
```
The PING timeout appears to not be delayed by the PING/PONG interval (while the subscription is?).

**Comment by sixlettervariables** [comment]
I added three new observables to see what was happening:
```csharp
        private readonly BehaviorSubject<NatsConnectionState> _connectionState = 
               new BehaviorSubject<NatsConnectionState>(NatsConnectionState.Disconnected);

        public NatsConnectionState ConnectionState 
        { 
            get
            {
                return _connectionState.Value;
            }
            private set
            {
                _connectionState.OnNext(value);
            }
        }

        public IObservable<NatsConnectionState> ConnectionStates => _connectionState;

        private readonly Subject<Unit> _onPinging = new Subject<Unit>();
        private readonly Subject<Unit> _onPong = new Subject<Unit>();

        public IObservable<Unit> OnPinging => _onPinging;

        public IObservable<Unit> OnPong => _onPong;
```
`OnNext` for OnPinging and OnPong are called where you would expect them.

Here is the new benchmark output:
```
Publish Only (5s PING/PONG interval, 10s PING timeout)
Connected
PING?
PONG!
1000000 in 00:00:06.9236366 (144432.77/s)
Disconnected
Publish Only (5s PING/PONG interval, 5s PING timeout)
Connected
PING?
Connecting
Disconnected
Exception encountered on test 746950 of 1000000 (00:00:05.0180379)
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 size, CancellationToken cancellationToken)
   at SimpleNatsClient.Connection.TcpConnection.<Write>d__8.MoveNext() in .\SimpleNatsClient\SimpleNatsClient\Connection\TcpConnection.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimpleNatsClient.Connection.NatsConnection.<Write>d__38.MoveNext() in .\SimpleNatsClient\SimpleNatsClient\Connection\NatsConnection.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimpleNatsClient.NatsClient.<Publish>d__11.MoveNext() in .\SimpleNatsClient\SimpleNatsClient\NatsClient.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BenchmarkTest.Benchmark.<BenchmarkPublishOnly>d__1.MoveNext() in .\SimpleNatsClient\benchmark\Benchmark.cs:line 43
```

**Comment by nataly87s** [comment]
@sixlettervariables Thanks!
I ran this locally but couldn't reproduce the exception. Were you using the default config file for the server?

**Comment by sixlettervariables** [comment]
Both with a default config and I tried it against our production cluster.

With timestamps printed (it looks like the Timeout doesn't take into account the DelaySubscription):
```
[2018-01-19T14:27:40.3827245+00:00] Connected
[2018-01-19T14:27:45.4352297+00:00] PING?
[2018-01-19T14:27:45.4762338+00:00] PING TIMEOUT!
[2018-01-19T14:27:45.8692731+00:00] Connected
...
```

**Comment by nataly87s** [comment]
I managed to reproduce, but I don't think the problem is with the timeout.
I think the exception is thrown when trying to publish while the client is reconnecting. I'll fix it when I get back home

**Comment by nataly87s** [comment]
@sixlettervariables can you take a look at #9 and see if it helps?
